### ISSUE TITLE
build failure, sudo npm build

### ISSUE THREAD

**Issue by aco7342** [omnisci/mapd-connector#33]
## :beetle: If bug
  - [x] Operating System and version: Ubuntu 16.04.03 LTS running inside virtualbox 5.0.40 r 115130 / Windows10
  - [x] Steps to reproduce (including dashboard link):
follow https://github.com/mapd/mapd-connector
`sudo npm install && sudo npm run build && sudo npm test`
  - [ ] Description of issue:
![mapdconnector_npmbuildfailure](https://user-images.githubusercontent.com/8000302/29790484-73a8c156-8c10-11e7-8211-13d806e8611b.png)
[2017-08-28T19_59_00_399Z-debug.zip](https://github.com/mapd/mapd-connector/files/1258241/2017-08-28T19_59_00_399Z-debug.zip)
please, anybody can helpme?

**Comment by mLuby** [comment]
Hi @aco7342 
These 4 warnings do not interfere with the library's operation.
<img width="810" alt="screen shot 2017-09-05 at 4 56 29 pm" src="https://user-images.githubusercontent.com/2483420/30088493-9087f502-925b-11e7-9da4-7ab4a8b91c3f.png">


What happens when you run these two commands from the repo root directory?
```
mocha test/integration.spec.js
karma start test/karma.conf.js
```

**Comment by jrajav** [comment]
Originating from ws (which we will upgrade along with Thrift soon anyway), and as mentioned, the posted messages are just warnings and don't indicate any real issues. Please re-open with any further details of build or test failures.
